---
- hosts: frontend-machines
  become: true
  tasks:
    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: create frontend directory on remote
      file:
        path: /home/ansible/frontend
        state: directory
        owner: ansible
        group: ansible
        mode: '0755'

    - name: Copy frontend dockerfile folder to remote
      copy:
        src: ./aits-docker-frontend/
        dest: /home/ansible/frontend/
        owner: ansible
        group: ansible
        mode: '0644'

    - name: build container image
      docker_image:
        name: frontend:latest
        build:
          path: /home/ansible/frontend
        source: build
        state: present

    - name: create container
      docker_container:
        name: frontendcontainer
        image: frontend:latest
        network_mode: host
        state: started


- hosts: backend-machines
  become: true
  tasks:
    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: create backend directory on remote
      file:
        path: /home/ansible/backend
        state: directory
        owner: ansible
        group: ansible
        mode: '0755'

    - name: Copy backend dockerfile folder to remote
      copy:
        src: ./aits-docker-backend/
        dest: /home/ansible/backend/
        owner: ansible
        group: ansible
        mode: '0644'

    - name: build container image
      docker_image:
        name: backend:latest
        build:
          path: /home/ansible/backend
        source: build
        state: present

    - name: create container
      docker_container:
        name: backendcontainer
        image: backend:latest
        network_mode: host
        state: started


- hosts: database-machines
  become: true
  tasks:
    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: create database directory on remote
      file:
        path: /home/ansible/database
        state: directory
        owner: ansible
        group: ansible
        mode: '0755'

    - name: Copy database dockerfile folder to remote
      copy:
        src: ./aits-docker-database/
        dest: /home/ansible/database/
        owner: ansible
        group: ansible
        mode: '0644'

    - name: build container image
      docker_image:
        name: database:latest
        build:
          path: /home/ansible/database
        source: build
        state: present

    - name: create container
      docker_container:
        name: databasecontainer
        image: database:latest
        network_mode: host
        state: started
